import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import db from "@/db";
import { workspaces } from "@/db/schema/workspaces";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await db.select().from(workspaces)

  console.log(data)
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
